### ISSUE TITLE
Views' doc missing when on same route and using same class

### ISSUE THREAD

**Issue by TheDan64** [SurveyMonkey/pyramid_autodoc#8]
Hi,

It seems to be the case that when I have multiple views on the same route that are both from the same class(typical for CRUD endpoints), the docs for those views don't generate at all.

Example:

``` python
config.add_route('my-route', '/my/path/')
config.add_view(
    Foo,
    attr='read',
    route_name='my-route',
    request_method='GET',
)
config.add_view(
    Foo,
    attr='update',
    route_name='my-route',
    request_method='PUT',
)
```

Seems to not generate any docs whatsoever for those two views when running make html. Also, this may be a separate issue, but if you take the above code and give the views separate routes so that they do appear, both will use the Foo's class docstring instead of the read and update method's doc strings which I found unintuitive.

**Comment by sontek** [comment]
@TheDan64 Sorry, I didn't notice this issue. I'll fix it tomorrow for you!

**Comment by TheDan64** [comment]
@sontek Thanks, looking forward to it!

**Comment by TheDan64** [comment]
@sontek Any update on this?

**Comment by sontek** [comment]
@TheDan64 Sorry, I forgot about this.  Here is the PR to fix it:

https://github.com/SurveyMonkey/pyramid_autodoc/pull/9

any chance you can test it?

**Comment by TheDan64** [comment]
Sure! I will take a look, thanks!

**Comment by TheDan64** [comment]
@sontek When I build and pip install from source, I get this message:
```bash
Processing /home/dkolsoi/repos/pyramid_autodoc/dist/pyramid_autodoc-1.0.1.dev1.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-pDbYJH-build/.eggs/setuptools_git-1.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/home/dkolsoi/venv/local/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/home/dkolsoi/venv/local/lib/python2.7/site-packages/pbr/util.py", line 264, in cfg_to_args
        wrap_commands(kwargs)
      File "/home/dkolsoi/venv/local/lib/python2.7/site-packages/pbr/util.py", line 566, in wrap_commands
        cmdclass = ep.resolve()
      File "/home/dkolsoi/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named upload
    error in setup command: Error parsing /tmp/pip-pDbYJH-build/setup.cfg: ImportError: No module named upload
```

I can't find a module name upload, so I assume it's something else?

**Comment by TheDan64** [comment]
@sontek Any update on this?

**Comment by TheDan64** [comment]
Took a look at this again and we were using the version 0.0.7 back then. 1.0.0 doesn't seem to have those issues anymore. Thanks.
